// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeifp-eVlgEaJaRPBA8Q2XLnGDEmMwvhg',
    appId: '1:865759167202:android:fe6eaea0dd6387b47694bb',
    messagingSenderId: '865759167202',
    projectId: 'mentalhealth-a5faa',
    storageBucket: 'mentalhealth-a5faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY7wAvhq-w4ooDi0lvH_IN9ayasIvbegk',
    appId: '1:865759167202:ios:148f575bba1cfc057694bb',
    messagingSenderId: '865759167202',
    projectId: 'mentalhealth-a5faa',
    storageBucket: 'mentalhealth-a5faa.appspot.com',
    androidClientId: '865759167202-66k02ek565ljrdhint1nlkjfm0f8iqii.apps.googleusercontent.com',
    iosClientId: '865759167202-km0skn8fv3jof7i5utstd44v5moa97sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalhealth',
  );
}
